spring.application.name=unit-testing
spring.datasource.url=jdbc:postgresql://localhost:5432/unitTestG10
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
sonar.token=${SONAR_TOKEN:}
