public class ReporteEmpleadoBoletas {

	/*
	 * ELABORAR UN PROGRAMA QUE PERMITA INGRESAR MEDIANTE UN MENÚ LA INFORMACIÓN DE
	 * UN EMPLEADO, SU SALARIO Y SUS BOLETAS EMITIDAS. OPCIÓN 1: SE DEBE PEDIR EL
	 * NOMBRE Y EL TIPO DE EMPLEADO (CONTRATADO O NOMBRADO) OPCIÓN 2: SE DEBE
	 * INGRESAR EL SALARIO MENSUAL, NÚMERO DE BOLETAS EMITIDAS Y NÚMERO DE MES EN
	 * CURSO. OPCIÓN 3: ELABORAR EL REPORTE ASCII (VALIDAR QUE LOS DATOS HAYAN SIDO
	 * INGRESADOS) UTILIZAR STRING.FORMAT() PARA GENERAR EL REPORTE. ALMACENE EL
	 * REPORTE EN UNA VARIABLE STRING.
	 */

	public static void main(String[] args) {

		
		
		
		
		
		
	}
}
