spring.application.name=ms-seguridad

spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update

token.api=sk_7701.y0uLrT7FJyzCkN2zotD3R23j02ZMYoRU

key.signature=KXRFofHDLHsTKRS5Ljw9uoyCMyNTPTJZeEe26oe9oi4CG9WSSKZCHbOTad6eBgSE1rp3zTQXHYonpBtAw0k9zw==
