spring.application.name=ms-seguridad

spring.datasource.url=jdbc:postgresql://localhost:5432/seguridad
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update

token.api=${EXTERNAL_API_TOKEN:}

key.signature=${JWT_SIGNATURE_KEY:}
