spring.application.name=apis-externas
spring.datasource.url=jdbc:postgresql://localhost:5432/bdjava14
spring.datasource.username=postgres
spring.datasource.password=admin

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

decoleta.token=sk_7701.y0uLrT7FJyzCkN2zotD3R23j02ZMYoRU
decoleta.base-url:https://api.decolecta.com

logging.level.root=debug

mock.base-url=http://localhost:8080
spring.cloud.openfeign.client.config.mockClient.connectTimeout=8000
spring.cloud.openfeign.client.config.mockClient.readTimeout=8000