//CLASE ABSTRACTA QUE REPRESENTA EL CONCEPTO GENERAL DE FIGURA.
//AQUI APLICO ESPECIALIZACION, YA QUE CIRCULO Y CUADRADO SON TIPOS DE FIGURA.
//TAMBIEN USO METODOS ABSTRACTOS PARA FORZAR A CADA SUBCLASE A DEFINIR SU PROPIA VERSION.

public abstract class  Figura {
	
	// METODO ABSTRACTO QUE DEBERA SER IMPLEMENTADO POR TODAS LAS FIGURAS CONCRETAS.
	  public abstract double calcularArea();
	
}


