spring.application.name=ms-register-hexa
#spring.datasource.url=jdbc:postgresql://localhost:5432/hexagonalG14
#spring.datasource.username=${DB_USERNAME:postgres}
#spring.datasource.password=${DB_PASSWORD:}
spring.jpa.hibernate.ddl-auto=update
#token.api=${EXTERNAL_API_TOKEN:}

#COnfiguracion a Vault Local
#spring.cloud.vault.uri=http://localhost:8200
spring.config.import=vault://
spring.cloud.vault.host=localhost
spring.cloud.vault.port=8200
spring.cloud.vault.scheme=http
spring.cloud.vault.application-name=ms-register-hexa
spring.cloud.vault.token=${TOKEN_VAULT}
