//INTERFAZ QUE DEFINE LA CAPACIDAD DE DIBUJAR.
//SE USA COMO UN COMPORTAMIENTO ADICIONAL, INDEPENDIENTE DE LA JERARQUIA FIGURA.

public interface Dibujable {

	// METODO QUE OBLIGA A LAS CLASES CONCRETAS A PROVEER SU PROPIA IMPLEMENTACION.
	void dibujar();
}


