//INTERFAZ QUE DEFINE EL COMPORTAMIENTO DE ROTACION.
//LA UTILIZO PARA APLICAR HERENCIA MULTIPLE A TRAVES DE INTERFACES,
//YA QUE UNA CLASE PUEDE IMPLEMENTAR VARIAS INTERFACES SIMULTANEAMENTE.

public interface Rotable {

	// METODO QUE CADA CLASE CONCRETA DEBERA IMPLEMENTAR.
	void rotar();
}

