spring.application.name=unit-testing
spring.datasource.url=jdbc:postgresql://localhost:5432/unitTestG10
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
sonar.token=625740f846c268a1858e448bc91769a6bb40302b